---
- name: Set root password to Vagrant
  user:
    name: root
    password: '{{ "vagrant" | password_hash("sha512", "salt123") }}'

- name: Install core stack
  yum:
    name:
    - vim
    - java-1.8.0-openjdk
    - wget
    - curl
    - unzip
    - nc
    state: present

- name: Set JAVA_HOME
  copy:
    content: JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk
    dest: /etc/environment
