---
- hosts: localhost
  tasks:
    - name: Template ansible hosts file
      template: 
        src: ansible_roles/roles/ansible-tdp-common-actions/templates/ansible-hosts.j2
        dest: inventory/hosts

    - name: Template Vagrant file
      template: 
        src: ansible_roles/roles/ansible-tdp-common-actions/templates/Vagrantfile.j2
        dest: Vagrantfile

    - name: Refresh inventory to load newly generated ansible inventory
      meta: refresh_inventory