---

  krb_pkg:
  - krb5-kdc
  - krb5-admin-server
  - python-selinux

  krb_service:
  - krb5-kdc
  - krb5-admin-server

  kdc_conf_path: /etc/krb5kdc/kdc.conf
  kadm5_acl_path: /etc/krb5kdc/kadm5.acl
